### ISSUE TITLE
Problem Getting Fields - Response Size exceeded when calling API method

### ISSUE THREAD

**Issue by eidylon** [EncompassRest/EncompassRest#217]
We're trying to get a list of all the fields in Encompass, but are having an issue. 

We calling `client.Pipeline.GetCanonicalNamesAsync()`, but it is crapping out blowing out the response size because they have a lot of fields. This is the error we are getting... 

    EncompassRest.EncompassRestException: GetCanonicalNamesAsync
    {"message":"Response exceeds maximum size (6 MB)"}
       at EncompassRest.ApiObject.<SendFullUriAsync>d__37`1.MoveNext()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at DataPull.Connections.Encompass.GetFields() in D:\TFS Local Repo\Ignite\Data Pull\EncompassAPI\datapull\Connections\Encompass.cs:line 94
       at DataPull.Processors.VerifyFieldsProcessor.BeginProcessing() in D:\TFS Local Repo\Ignite\Data Pull\EncompassAPI\datapull\Processors\VerifyFieldsProcessor.cs:line 31
    ---> (Inner Exception #0) EncompassRest.EncompassRestException: GetCanonicalNamesAsync
    {"message":"Response exceeds maximum size (6 MB)"}
       at EncompassRest.ApiObject.<SendFullUriAsync>d__37`1.MoveNext()<---

How can I go about increasing the allowable response size so that this will work? 
Based on some googling, the most promising thing I found was: 
`    HttpWebRequest.DefaultMaximumResponseHeadersLength = 600000; `
before placing the web call, but that didn't seem to do anything.

**Comment by TylerBrinkley** [comment]
That's because it's a server side limitation due to their use of AWS. You may want to look into if there is a pagination version of the call.

**Comment by eidylon** [comment]
Thanks for the info. Looked into the AWS stuff, and was able to pass that along to management above.
