### ISSUE TITLE
Enums.Net 3 breaks everything

### ISSUE THREAD

**Issue by tlambert** [EncompassRest/EncompassRest#304]
I try and keep my NuGet packages up to date and version 3.0.1 breaks this and can't initialize the client and not sure what else.  Reverting back to 2.3.2 works so not a huge deal but wanted let you know.

The type initializer for 'CustomContractResolver' threw an exception.

Method not found: '!!0 EnumsNET.Enums.Validate(!!0, System.String)'.
   at EncompassRest.Utilities.JsonHelper.CustomContractResolver.GetBackingFieldInfo(Type type, String propertyName)
   at EncompassRest.Utilities.JsonHelper.PrivateContractResolver.PopulateShouldSerializeMethod(JsonProperty property, PropertyInfo propertyInfo)
   at EncompassRest.Utilities.JsonHelper.CustomContractResolver.CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at EncompassRest.Utilities.JsonHelper.PrivateContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at EncompassRest.Utilities.JsonHelper.FromJson[T](TextReader reader)
   at EncompassRest.Utilities.JsonHelper.<ReadAsAsync>d__27`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.ApiObject.<SendFullUriAsync>d__41`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.Token.AccessToken.<GetTokenAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.EncompassRestClient.<CreateAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EncompassAPIUtils.Form1.<button1_Click>d__1.MoveNext()

**Comment by TylerBrinkley** [comment]
Thanks, yes this is a known issue. It's good to have it logged here though. The next version of `EncompassRest` will use the latest version of `Enums.NET`.
