### ISSUE TITLE
Issue when using Encompass SDK to fetch loan Details

### ISSUE THREAD

**Issue by rghkrish** [EncompassRest/EncompassRest#328]
.NET Core Version : 3.1
EncompassRest SDK Version: 1.2.0

When i do encompassRestClient.Loans.GetLoanAsync, I get the following error.
```

System.Exception: Error converting value "N/A" to type 'System.Decimal'. Path 'hmda.rateSpread', line 1, position 26629.    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at EncompassRest.NAConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at EncompassRest.Utilities.JsonHelper.FromJson[T](TextReader reader)
   at EncompassRest.Utilities.JsonHelper.ReadAsAsync[T](HttpContent content)
   at EncompassRest.ApiObject.DirtyFuncCache`1.<>c.<<-cctor>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at EncompassRest.ApiObject.SendFullUriAsync[T](HttpMethod method, String requestUri, String queryString, HttpContent content, String methodName, String resourceId, CancellationToken cancellationToken, Func`2 func, Boolean throwOnNonSuccessStatusCode, Boolean disposeResponse)
   at EncompassRest.Loans.Loans.GetLoanAsync(String loanId, IEnumerable`1 entities, CancellationToken cancellationToken)
```

This looks like it is coming from inside the SDK, so I'm not sure what to do about it.

Also I see this is a conversion issue where it breaks when a conversion from "N/A" to a decimal type is attempted. Is this a case where invalid data was entered and no validation was done at that end?

Any help would be hugely appreciated.

**Comment by rghkrish** [comment]
Thank you. It'd be super cool if we could get a fix cos we've got stuff breaking in production because of this.

**Comment by TylerBrinkley** [comment]
@rghkrish Could you pull down the repo locally and reference it directly to confirm it fixes your error?

**Comment by rghkrish** [comment]
Hi @TylerBrinkley, Yes it fixes the error :). When might we expect a patch release to nuget?

**Comment by TylerBrinkley** [comment]
v1.2.1 is released to nuget which includes this fix.

**Comment by rghkrish** [comment]
@TylerBrinkley 

I'd have liked to open a new issue but since this one looked super similar so I'm adding it here.

```
System.Exception: Error converting value "N.A" to type 'System.Decimal'. Path 'hmda.rateSpread', line 1, position 32274.    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at EncompassRest.NAConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at EncompassRest.Utilities.JsonHelper.FromJson[T](TextReader reader)
   at EncompassRest.Utilities.JsonHelper.ReadAsAsync[T](HttpContent content)
   at EncompassRest.ApiObject.DirtyFuncCache`1.<>c.<<-cctor>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at EncompassRest.ApiObject.SendFullUriAsync[T](HttpMethod method, String requestUri, String queryString, HttpContent content, String methodName, String resourceId, CancellationToken cancellationToken, Func`2 func, Boolean throwOnNonSuccessStatusCode, Boolean disposeResponse)
```

I get this with version 1.2.1 on .NET Core 3.1. Looks like a "N.A" type to decimal conversion error.

**Comment by gashach** [comment]
Should we convert the NA system to remove all "." and then ignore case for "na" comparrison?
