### ISSUE TITLE
RefreshAsync() intermittent error/issue

### ISSUE THREAD

**Issue by paulmoseley** [EncompassRest/EncompassRest#407]
I'm using the new set of methods (ExportAttachmentsAsync, RefreshAsync, and DownloadAsync) to grab the contents of a loan's pdf document from the eFolder.  This works well 95-99% of the time, but I occasionally get an error from the RefreshAsync method, which seems to indicate that the ExportAttachmentsAsync method didn't work.  What's odd is that I can run the service I've built around these methods successfully against the same loan(s) moments/minutes later.  The error seems to be completely random, it's not tied to any loan or anything else that I can fathom.  The error I get from RefreshAsync is "Value cannot be null. (Parameter 'file')"; this implies that the 'job' variable that's returned from the ExportAttachmentsAsync method is missing the 'file' object.

The service that uses this code processes anywhere from 30-100 loans per run.  Most of the time it runs successfully the first time, but sometimes it takes multiple runs (from 2 to 4) to get it to run successfully, with the error occurring on a different loan each time.  I'm pretty perplexed by all this, since the error doesn't appear consistently, but seems to appear randomly.  Since this error is probably pretty deep in either the bindings or (more likely) the Encompass API calls it's using, I'm thinking about trying some workarounds (like re-trying the ExportAttachmentsAsync method if it returns a null value in the 'file' object), but wanted to check here in case anyone has any other ideas.  Does this sound like an Encompass API issue, that I should open a ticket with ICE for?

I'll cut-and-paste the method I use to find and grab the pdf contents, and more detail on the error I'm getting below.  First the method:

        /// <summary>
        /// SearchLoanForAddressCertDocument - searches for the Address Certification document for the loan with the GUID passed
        /// </summary>
        /// <param name="loanGuid">Loan GUID to use in search for Address Certification document.</param>
        /// <returns>Async Task - byte array with document/attachment contents</returns>
        public virtual async Task<byte[]> SearchLoanForAddressCertDocumentAsync(string loanGuid)
        {
            Loan loan = await Repo.GetLoanDataByGuidAsync(loanGuid, new List<string> { "EdmDocument" });
            List<LoanAttachment> loanDocumentAttachments = await loan.LoanApis.Attachments.GetAttachmentsAsync(CancellationToken.None);
            var loanDocumentAttachment = loanDocumentAttachments.FirstOrDefault(x =>
                (x.Title?.Contains("Address Certification") ?? false)
                && (x.Document?.EntityName?.Contains("Address Certification") ?? false)
                && x.IsActive == true
                && !string.IsNullOrEmpty(x.AttachmentId)
                && !string.IsNullOrEmpty(x.Document.EntityUri)
            );

            if (loanDocumentAttachment == null)
                return null;

            var job = await loan.LoanApis.Attachments.ExportAttachmentsAsync(new EntityReference[] { loanDocumentAttachment });

            int maxChecks = 5;
            for (int i = 0; i <= maxChecks; i++)
            {
                await job.RefreshAsync();

                if (job.Status == "Success" || job.Status == "Failed")
                {
                    break;
                }

                await Task.Delay(1000);
            }

            if (job.Status != "Success")
            {
                Log.Info($"Could not retrieve Address Certification pdf for loan {loanGuid}");
                return null;
            }

            return await job.DownloadAsync();
        }

And now the error details (which include references to my code along with the .NET bindings/API):

ERROR | 21:19:16.5435 | AddressCertificationExtract.AddressCertificationExtractFiles.CreateFiles | Address Certification Extract process failed with this message: Value cannot be null. (Parameter 'file').  Process failed while attempting to retrieve loan info for loans funded on 1/19/2022.  Current loan detail: {"loanGuid":"98e439c1-6bce-432e-b5e6-27831f930df6","fields":{"Fields.GUID":"{98e439c1-6bce-432e-b5e6-27831f930df6}","Fields.364":"8501527347","Fields.4002":"White"}}.
System.ArgumentNullException: Value cannot be null. (Parameter 'file')
   at EncompassRest.EFolder.ExportAttachmentsJob..ctor(String jobId, FileResponse file)
   at lambda_method3732(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at EncompassRest.Utilities.JsonHelper.PopulateFromJson(TextReader reader, Object target)
   at EncompassRest.Utilities.JsonHelper.PopulateAsync(HttpContent content, Object target)
   at EncompassRest.ApiObject.<>c__DisplayClass41_0.<<PopulateDirtyInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at EncompassRest.ApiObject.SendFullUriAsync[T](HttpRequestMessage request, String methodName, String resourceId, CancellationToken cancellationToken, Func`2 func, Boolean throwOnNonSuccessStatusCode, Boolean disposeResponse)
   at AddressCertificationExtract.AddressCertificationExtractFiles.SearchLoanForAddressCertDocumentAsync(String loanGuid) in C:\a\1\s\NextGen\UserDriven\Website\API\AddressCertificationExtract\AddressCertificationExtractFiles.cs:line 133
   at AddressCertificationExtract.AddressCertificationExtractFiles.CreateFiles() in C:\a\1\s\NextGen\UserDriven\Website\API\AddressCertificationExtract\AddressCertificationExtractFiles.cs:line 82
ERROR | 21:19:16.6218 | HomeLending.Controllers.AddressCertExtController.DateFunding | Error generating the Address Certification Extract pdf files
System.ArgumentNullException: Value cannot be null. (Parameter 'file')
   at EncompassRest.EFolder.ExportAttachmentsJob..ctor(String jobId, FileResponse file)
   at lambda_method3732(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at EncompassRest.Utilities.JsonHelper.PopulateFromJson(TextReader reader, Object target)
   at EncompassRest.Utilities.JsonHelper.PopulateAsync(HttpContent content, Object target)
   at EncompassRest.ApiObject.<>c__DisplayClass41_0.<<PopulateDirtyInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at EncompassRest.ApiObject.SendFullUriAsync[T](HttpRequestMessage request, String methodName, String resourceId, CancellationToken cancellationToken, Func`2 func, Boolean throwOnNonSuccessStatusCode, Boolean disposeResponse)
   at AddressCertificationExtract.AddressCertificationExtractFiles.SearchLoanForAddressCertDocumentAsync(String loanGuid) in C:\a\1\s\NextGen\UserDriven\Website\API\AddressCertificationExtract\AddressCertificationExtractFiles.cs:line 133
   at AddressCertificationExtract.AddressCertificationExtractFiles.CreateFiles() in C:\a\1\s\NextGen\UserDriven\Website\API\AddressCertificationExtract\AddressCertificationExtractFiles.cs:line 82
   at HomeLending.Controllers.AddressCertExtController.DateFunding(DateTime fundingDate) in C:\a\1\s\NextGen\UserDriven\Website\API\HomeLending\Controllers\AddressCertExtController.cs:line 66

end of message :)

**Comment by TylerBrinkley** [comment]
It honestly seems like an API issue where the file property intermittently is not being returned when the `RefreshAsync` method tries to get the job details.

**Comment by paulmoseley** [comment]
Thanks, Tyler!  I'll include that idea (checking to see whether job.File is null after a successful RefreshAsync call) in my coding workarounds.  I'll also open a ticket with ICE/Ellie, and will keep this issue open here until I get more information from them, and/or find a code-based workaround...

**Comment by paulmoseley** [comment]
I created a topic in the ICE/Ellie Mae User Forums about a week ago, and got a few views (mostly mine) but no responses yet :(.  I just got a case added for this, I'll update this item with any updates from there, or anywhere...

**Comment by paulmoseley** [comment]
OK, and months later...without ICE/Ellie Mae actually doing anything...the issue went away.  The 5 seconds I'm allowing for the RefreshAsync method to grab the pdf once the job is created seems to be enough time as well (I had some failures there, but none in the past week or so, and those failures were rare).  The code workaround I introduced (which attempts to create the job multiple times if it returns a null job) didn't get deployed until after the issue resolved itself, so I can't tell if it worked.  My suspicion is that the issue was related to some combination of server and network issues.  Anyway, I'll close this out now.
