### ISSUE TITLE
Newtonsoft.json Deserialize/Parsing Issue with Encompass 22.3 Upgrade

### ISSUE THREAD

**Issue by zackwertz** [EncompassRest/EncompassRest#414]
Facing an issue with 'GetLoanAsync' method in Testing Environment after Encompass 22.3 Upgrade . Newtonsoft.Json is throwing an error for all loans in all testing environments we have tried with error: 
Input string '10000.0' is not a valid integer. Path 'applications[0].employment[0].monthlyIncomeAmount', line 1, position 13363. 
(10000.0 value changes based on loan)

Any information on why this may be occurring would be greatly appreciated. Seems to be related to the 22.3 Upgrade

Stack Trace is below:

at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at EncompassRest.Utilities.JsonHelper.FromJson[T](TextReader reader)
   at EncompassRest.Utilities.JsonHelper.<ReadAsAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.ApiObject.DirtyFuncCache`1.<>c.<<-cctor>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.ApiObject.<SendFullUriAsync>d__44`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EncompassRest.Loans.Loans.<GetLoanAsync>d__11.MoveNext()

**Comment by JSalusky** [comment]
![UpdatedFields](https://user-images.githubusercontent.com/46973427/191605546-884c4435-539b-456a-8c8e-acdb323494e7.png)
 
Some field definitions had been updated for this release - which broke the library call for 'GetLoanAsync' method

**Comment by TylerBrinkley** [comment]
As I no longer maintaining this library I'd suggest someone regenerate the entities for the latest schema or at the least just manually update these specific properties to be decimal's instead of int's.

**Comment by zackwertz** [comment]
Thank you both for the information.
Tyler, do you know if there are any other current maintainers now that you have moved to other opportunities? 
I am trying to familiarize myself with EntityGenerator and will try out some local updates before replying back with my findings

**Comment by mtucker6784** [comment]
@zackwertz , this isn't a shameless plug, and I don't know enough currently to apply to be a maintainer for this awesome library that Tyler created, but I did update the code to properly reflect 22.3's changes ---

https://github.com/mtucker6784/EncompassRest

hope this helps in the interim!

**Comment by zackwertz** [comment]
Appreciate it Michael! I've had some build issues after pulling the code that I've been working on, but will verify your updates and chime in with any thoughts/questions I may come up with during testing.
More to come!

**Comment by tlambert** [comment]
Employment.cs
        private DirtyValue<decimal?>? _monthlyIncomeAmount;
        public decimal? MonthlyIncomeAmount { get => _monthlyIncomeAmount; set => SetField(ref _monthlyIncomeAmount, value); }
ReoProperty.cs
        private DirtyValue<decimal?>? _purchasePrice;
        public decimal? PurchasePrice { get => _purchasePrice; set => SetField(ref _purchasePrice, value); }
Residence.cs
        private DirtyValue<decimal?>? _rent;
        public decimal? Rent { get => _rent; set => SetField(ref _rent, value); }
Valuation.cs
        private DirtyValue<decimal?>? _appraisedValue;
        public decimal? AppraisedValue { get => _appraisedValue; set => SetField(ref _appraisedValue, value); }

This was all I changed and it seems to be working fine.  even updating newtonsoft.json.
